#pragma once

#define WITH_SOURCE_INFO
//#define EAGER_INTERBLOCK_CHECK
#define MONITOR_SHARED_MEMORY
#define MONITOR_GLOBAL_MEMORY
#define EAGER_COLUMN_MERGE
#define EAGER_LOG_MERGE

#define MAX_SHARED_BUFFER_LENGTH 1024
#define MAX_BLOCKS_NUM 65536
#define MAX_THREADS_NUM 1024
//made scalarProd slower.
//#define RECURSIVE_MERGE

//don't need locks if the inter-block races are checked inside a separate kernel after
//the target program terminates.
#ifdef EAGER_INTERBLOCK_CHECK
#define USE_LOCKS
#undef EAGER_COLUMN_MERGE
#endif

#define INTERBLOCK_CHECKS
#define INTRABLOCK_GM_CHECKS
#define INTRABLOCK_CHECKOVERLAPS
#define MERGELIKE_SEARCH
#define OPTIMISTIC_SETCHECKS
#define ENABLE_BLOCKSETS
#define DEDUP_RWSETS 
#define COMPRESS_BS_BUFFER
#define BUFFERED_COMPRESSION
#define BUFFER_SIZE 4
// for SM 3.5
#define MAX_RESIDENT_BLOCKS_PER_SM 16
#define DEFAULT_BLOCKS_TO_TRACK_SM 16
#define DEFAULT_BLOCKS_TO_TRACK_GM 16
#define DEFAULT_INITIAL_TRSSIZE_SM 1600 * 4
#define DEFAULT_INITIAL_TWSSIZE_SM 1600 * 4
#define DEFAULT_INITIAL_TRSSIZE_GM 1600 * 4
#define DEFAULT_INITIAL_TWSSIZE_GM 1600 * 4
#define DEFAULT_INITIAL_BRSSIZE 1024 * 1024
#define DEFAULT_INITIAL_BWSSIZE 1024 * 1024
#define GMEM_RACES_BUFFER_SIZE 1024 * 1024
#define SMEM_RACES_BUFFER_SIZE 1024 * 1024
#define DEFAULT_TS_INSERT_SEARCH_RANGE 4
#define DEFAULT_BS_MERGE_SEARCH_RANGE 4

//#define DEFAULT_TS_INSERT_SEARCH_RANGE DEFAULT_INITIAL_TRSSIZE_GM

<<<<<<< HEAD
//#define ENABLE_SAMPLE_TIME
=======

>>>>>>> 0812110a738a6531e4551dd20ed6336881fc2726
#define PRINT_SUMMARY
// for debugging/profiling use
#define ENABLE_COUNTERS
//#define SEQ_COMPRESS_VERIFY
#define ASSERTS_ON

#define BINARY_SEARCH

#define VERBOSE_OUTPUT

#ifdef EAGER_INTERBLOCK_CHECK
#define CURD_MODE "Eager"
#else
#define CURD_MODE "Lazy"
#endif

#define SYNCTHREADS_CNC
//#define STRICT_DEDUP
#define STOP_AT_FIRST_RACE
#define BARRIER_CHECKS
//#define SORT_TS
